### ISSUE TITLE
to resize it to a given CGRect?

### ISSUE THREAD

**Issue by aelam** [AliSoftware/UIImage-Resize#11]
to resize it to a given CGRect?
how?

**Comment by AliSoftware** [comment]
I don't understand the question. Doesn't `resizedImageToSize:` fits the bill?!

**Comment by aelam** [comment]
your description means cropping with a specified CGRect, but your method just can resize with a CGSize. It's different.

**Comment by AliSoftware** [comment]
I still don't get it. Where did you read anything about my methods cropping the images?

As their name (and the README documentation) suggests, they were always meant to resize, never crop. Did I miss / let some typo slip somewhere in my documentation perhaps?

**Comment by AliSoftware** [comment]
Oh I just got it, you were neither asking how to crop nor talking about the documentation in the code or in the README, but just talking about the text **in the GitHub description** of the repository, right?

I just fixed the typo in the description, replacing `CGRect` with `CGSize`.

> Category to add some resizing methods to the UIImage class, to resize it to a given ~~CGRect~~ **CGSize** — or fit in a ~~CGRect~~ **CGSize** keeping aspect ratio

Thanks for spotting it!

**Comment by aelam** [comment]
cool
