### ISSUE TITLE
unrecognized selector sent to instance 0x1cdc3dc0

### ISSUE THREAD

**Issue by zuil7** [AliSoftware/UIImage-Resize#2]
Hi,

```
   I tried using UIImage-Resize on my project. I got an error (see below). It doesn't go inside the function.
```

2012-05-24 14:10:03.619 ScalingImageSample[928:607] -[UIImage resizedImageToFitInSize:scaleIfSmaller:]: unrecognized selector sent to instance 0x1cdc3dc0
2012-05-24 14:10:03.621 ScalingImageSample[928:607] CoreAnimation: ignoring exception: -[UIImage resizedImageToFitInSize:scaleIfSmaller:]: unrecognized selector sent to instance 0x1cdc3dc0

I use this code to call the function

UIImage\* scaledImgV = [self.imgSrc resizedImageToFitInSize:imgContainer.bounds.size scaleIfSmaller:NO];
NSLog(@"Scaled image V (%@): %@",scaledImgV,NSStringFromCGSize(scaledImgV.size));
imgContainer.image = scaledImgV;

Hope you can fixed it. 

Thanks!

**Comment by zuil7** [comment]
Just need to add the class manual in the compiler sources. Thanks!

**Comment by AliSoftware** [comment]
Hello

Are you sure you included the .m file in your project and more importantly
in your target ? If you select the .m file, is it marked to be included in
your application target (so compiled & linked with the final application)
like any other .m file in your project ?

On Thu, May 24, 2012 at 8:20 AM, zuil7 <
reply@reply.github.com

**Comment by AliSoftware** [comment]
Wooops didn't see your auto-answer and that you solved your problem !
(And in fact that was the case I describe, if you don't include the .m file in the target, it is not added in the "Compile Sources" phase and is not linked with the final app)
