### ISSUE TITLE
White line after resize - fixed by adding floor()

### ISSUE THREAD

**Issue by discobean** [AliSoftware/UIImage-Resize#3]
I noticed a white line on the right or the bottom after doing a resizedImageToFitInSize on iPhone4 to 640x480 size.

The fix was to add a floor() when setting/calculating the destination size in this method see below:

```
    if (wRatio < hRatio) {
        //NSLog(@"Width imposed, Height scaled ; ratio = %f",wRatio);
        dstSize = CGSizeMake(boundingSize.width, floor(srcSize.height * wRatio));
    } else {
        //NSLog(@"Height imposed, Width scaled ; ratio = %f",hRatio);
        dstSize = CGSizeMake(floor(srcSize.width * hRatio), boundingSize.height);
    }
```

Apart from that the code has been great, thankyou

**Comment by AliSoftware** [comment]
Thanks a lot for the suggestion. I merged your code in my latest commit.
