### ISSUE TITLE
Retina Support

### ISSUE THREAD

**Issue by discobean** [AliSoftware/UIImage-Resize#4]
For the -(UIImage*)resizedImageToSize:(CGSize)dstSize method I also added retina support by adding options when starting the imagecontext

```
UIGraphicsBeginImageContextWithOptions(dstSize, YES, 0);
```

Although this might not be a requirement for everybody.  But I found it useful.

**Comment by AliSoftware** [comment]
Thanks a lot for the suggestion. I merged your code in my latest commit.
